In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
claimants = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\claimants.csv")
del claimants['CASENUM']
claimants

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [6]:
import statsmodels.formula.api as sm
logit_model = sm.logit('ATTORNEY~CLMAGE+LOSS+CLMSEX+CLMINSUR+SEATBELT', data = claimants).fit()
logit_model.summary()

Optimization terminated successfully.
         Current function value: 0.587523
         Iterations 8


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               ATTORNEY   No. Observations:                 1096
Model:                          Logit   Df Residuals:                     1090
Method:                           MLE   Df Model:                            5
Date:                Fri, 10 Sep 2021   Pseudo R-squ.:                  0.1505
Time:                        14:13:18   Log-Likelihood:                -643.92
converged:                       True   LL-Null:                       -758.05
Covariance Type:            nonrobust   LLR p-value:                 2.546e-47
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.2000      0.247     -0.810      0.418      -0.684       0.284
CLMAGE         0.0065      0.003      1.952      0.051   -2.75e-05       0.013
LOSS          -0.3850      0.035    -11.050      0.000      -0.453      -0.317
CLMSEX         0.4330      0.136      3.191      0.001       0.167       0.699
CLMINSUR       0.6022      0.231      2.606      0.009       0.149       1.055
SEATBELT      -0.7811      0.566     -1.380      0.168      -1.891       0.329
==============================================================================
"""

In [8]:
logit_model.params

Intercept   -0.199978
CLMAGE       0.006487
LOSS        -0.385044
CLMSEX       0.432996
CLMINSUR     0.602173
SEATBELT    -0.781079
dtype: float64

In [10]:
np.exp(logit_model.params)

Intercept    0.818749
CLMAGE       1.006508
LOSS         0.680421
CLMSEX       1.541870
CLMINSUR     1.826083
SEATBELT     0.457912
dtype: float64

In [11]:
predict = logit_model.predict(pd.DataFrame(claimants[['CLMAGE', 'LOSS', 'CLMINSUR', 'CLMSEX', 'SEATBELT']]))
predict

0       0.000003
1       0.501679
2       0.576291
3       0.452142
4       0.641570
          ...   
1335         NaN
1336    0.427275
1337    0.740790
1338    0.281230
1339    0.682417
Length: 1340, dtype: float64

In [12]:
from sklearn.metrics import confusion_matrix
pcnf_matrix = confusion_matrix(claimants['ATTORNEY'], predict > 0.5)
pcnf_matrix

array([[487, 198],
       [262, 393]], dtype=int64)

In [15]:
(487+393)/(487+198+262+393)

0.6567164179104478

In [13]:
from sklearn.metrics import accuracy_score
Score = accuracy_score(claimants['ATTORNEY'], predict > 0.5)
Score

0.6567164179104478

In [14]:
# Accuracy score can be imporved by
# 1 Handling the missing values
# 2 Transformation methods
# 3 Consider the importance of variables

# Method 2

In [16]:
claimants = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\claimants.csv")
del claimants['CASENUM']
claimants

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [19]:
claimants.isnull().sum()

ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [23]:
# CLMSEX, CLMINSUR, SEATBELT are categorical -> replace with Mode
# CLMAGE is continuous -> replace with Mean

In [24]:
claimants['CLMAGE'].fillna(claimants['CLMAGE'].mean(), inplace = True)
claimants

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0            0     0.0       1.0       0.0  50.000000  34.940
1            1     1.0       0.0       0.0  18.000000   0.891
2            1     0.0       1.0       0.0   5.000000   0.330
3            0     0.0       1.0       1.0  31.000000   0.037
4            1     0.0       1.0       0.0  30.000000   0.038
...        ...     ...       ...       ...        ...     ...
1335         1     0.0       1.0       0.0  28.414422   0.576
1336         0     1.0       1.0       0.0  46.000000   3.705
1337         1     1.0       1.0       0.0  39.000000   0.099
1338         0     1.0       0.0       0.0   8.000000   3.177
1339         1     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [31]:
claimants['CLMSEX'].fillna(claimants['CLMSEX'].mode()[0], inplace=True)
claimants['CLMINSUR'].fillna(claimants['CLMINSUR'].mode()[0], inplace=True)
claimants['SEATBELT'].fillna(claimants['SEATBELT'].mode()[0], inplace=True)
claimants

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0            0     0.0       1.0       0.0  50.000000  34.940
1            1     1.0       0.0       0.0  18.000000   0.891
2            1     0.0       1.0       0.0   5.000000   0.330
3            0     0.0       1.0       1.0  31.000000   0.037
4            1     0.0       1.0       0.0  30.000000   0.038
...        ...     ...       ...       ...        ...     ...
1335         1     0.0       1.0       0.0  28.414422   0.576
1336         0     1.0       1.0       0.0  46.000000   3.705
1337         1     1.0       1.0       0.0  39.000000   0.099
1338         0     1.0       0.0       0.0   8.000000   3.177
1339         1     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [32]:
claimants.isnull().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [78]:
X = claimants.iloc[:, 1:].values
X

array([[ 0.   ,  1.   ,  0.   , 50.   , 34.94 ],
       [ 1.   ,  0.   ,  0.   , 18.   ,  0.891],
       [ 0.   ,  1.   ,  0.   ,  5.   ,  0.33 ],
       ...,
       [ 1.   ,  1.   ,  0.   , 39.   ,  0.099],
       [ 1.   ,  0.   ,  0.   ,  8.   ,  3.177],
       [ 1.   ,  1.   ,  0.   , 30.   ,  0.688]])

In [79]:
y = claimants.iloc[:, 0].values
y

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, random_state = 0)

In [81]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()

In [82]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [83]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [84]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,

In [85]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [86]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred, y_test)
cm

array([[ 73,  25],
       [113, 124]], dtype=int64)

In [88]:
(73+124)/(73+25+113+124)

0.5880597014925373

In [87]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.5880597014925373